name: Upload Release Asset

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching *

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
    
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Publish to WP.org
        uses: 10up/action-wordpress-plugin-deploy@master
        with:
          generate-zip: true
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: sold-out-badge-for-woocommerce
          
      - name: Upload Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{github.workspace}}/${{ github.event.repository.name }}.zip
          asset_name: sold-out-badge-for-woocommerce.zip
          asset_content_type: application/zip
